spring:
  datasource:
    #mysql local
    url: mysql://${{ MYSQLUSER }}:${{ MYSQLPASSWORD }}@${{ MYSQLHOST }}:${{ MYSQLPORT }}/${{ MYSQLDATABASE }}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

#  spring_profiles_active=prod
#  MYSQLHOST=containers-us-west-72.railway.app
#  MYSQLPORT=6830
#  MYSQLDATABASE=railway
#  MYSQLPASSWORD=ZHIeIqMdRw5wGpngEfXI
#  MYSQLUSER=root
#